### ISSUE TITLE
Cloudant DB access via MobileFirst Starter Container's Data Proxy does not work

### ISSUE THREAD

**Issue by kkkum** [MobileFirst-Platform-Developer-Center/WishlistiOS#1]
I'm trying to get the Cloudant DB Creation and Access via Data Proxy in the MobileFirst Start Container to work in the Native iOS sample - https://github.com/MobileFirst-Platform-Developer-Center/WishlistiOS

I followed the instructions documented in the Knowledge Center -
http://www-01.ibm.com/support/knowledgecenter/SSHS8R_7.1.0/com.ibm.worklight.deploy.doc/deploy/t_create_deploy_gs_container.html
http://www-01.ibm.com/support/knowledgecenter/SSHS8R_7.1.0/com.ibm.worklight.deploy.doc/deploy/t_using_cloudant_gscontainer.html?lang=en

I did some troubleshooting with the provided Native iOS sample ParkStore app with the MobileFirst Starter Container and Cloudant Data Proxy. The Catalog function works and the LocalStoreAdapter function also works. But the Cloudant DB access via Data Proxy does not work. When trying to create the remote Cloudant DB via the Data Proxy, the iOS app encounters the error "url parameter cannot be nil". See the extract with my debug logs below -

Reachability.isConnectedToCloudantDataProxy URL: Optional("Optional(\"http://XXX.XXX.XXX.XXX:XXXX\")/datastore")...
2015-10-26 19:06:11.061 ParkStore[64733:447248]
IMFDataManager initialized successfully:
CloudantToolkit Version: 1.1.1
CloudantToolkit Build Date: 20150911_0800
IMFData-Local Version: 1.1.1
IMFData-Local Build Date: 20150911_0800
Target URL: Optional("http://XXX.XXX.XXX.XXX:XXXX")/datastore/api/v1/apps/default

Manager remoteStore create error: Error Domain=Unify Code=100 "url parameter cannot be nil" UserInfo={NSLocalizedDescription=url parameter cannot be nil}

Reference the Bluemix support ticket opened for this issue: Ticket #5377-12087177

**Comment by IdanAdar** [comment]
This sample has been discontinued.
